### ISSUE TITLE
Navigate to "My Computer" in File System View

### ISSUE THREAD

**Issue by dmik** [dmik/qt-creator-os2#5]
Some file systems on OS/2 report ".." in the root directory of the drive. This entry gets propagated to Qt (see http://svn.netlabs.org/qt4/ticket/242) and in particular to the File System View pane of Qt Creator where selecting it presents the list of all available drives.

While it may look like a bug at first, it may also be a feature. Earlier I said speaking to Rudi:

Regarding "..". Yes, it looks like this behavior is unintended but are you sure it's a bug? It looks like a (handy) feature to me. The only other way to change drives in this view is to RMB on the header, select Choose Folder..., select the necessary drive from the popped file dialog etc., in other words much more actions to perform.

What do you think if we improve it a bit instead? E.g. by making sure ".." is always added to the root directory listing (even on Windows) and clicking it shows My Computer. We will also need to sort items in the My Computer list properly (they look unsorted now) and to make the header show "My Computer" (instead of ".." as now).

JFTR, this is a patch by Rudi to remove http://svn.netlabs.org/qt4/attachment/ticket/205/foldernavigationwidget.diff that completely disables this bug-o-feature.

**Comment by warped-rudi** [comment]
To be honest: I also thought of that as a useful feature.

**Comment by warped-rudi** [comment]
Thinking a bit more about this I came to the conclusion that it's not so easy to achieve. The problem is to fake the ".." entry on file systems that don't report it. This would require to inject non-existing directories into a QFileSystemModel, which appears to be much more complicated than to filter out existing ones. If we really want this functionality, it's most likely better to not include ".." in the directory list and add a "dir up" button somewhere.

**Comment by dmik** [comment]
I agree with you. Let's close this; it has nothing to do with the OS/2 port at least.
