### ISSUE TITLE
Upscaled folder icons in Project view

### ISSUE THREAD

**Issue by warped-rudi** [dmik/qt-creator-os2#6]
When a project contains files that are located in subdirectories other than the one in which the project file resides. I.e. something like:

SOURCES = src/file1.cpp
HEADERS = include/file1.h
FORMS = ui/file1.ui

the subfolder icons (here src, include and ui) get upscaled. This is a result of the fact that the toplevel folder icons are handled differently (they have overlays and the size is forced to 16x16) than the subfolder icons (queried directly from QStyle). Cause of the problem is, that there is no icon size set for the tree view widget. Thus - on OS/2 - a default size of 20x20 is assumed. However, the icons from common style are 16x16 and thus get upscaled.

**Comment by warped-rudi** [comment]
My quick fix can be found here: http://svn.netlabs.org/qt4/attachment/ticket/205/navigationtreeview.diff

It enforces 16x16 in NavigationTreeView, which is a base class of ProjectTreeView (and the XxxOutlineTreeViews). I guess, it would be sufficient to do this in the ProjectTreeView only, since it looks liek the Outline views are always feed with fixed size pixmaps.

Of course, we now have the situation that the File System view uses 20x20 icons while all the other Views use 16x16. But I think the effort to change all icons to 20x20 would be too big.

**Comment by warped-rudi** [comment]
About the above fix: Thinking a bit more about this: The icon size should be forced on any platform, not just on OS/2. The code should never rely on the fact that a small icon size is 16x16.

**Comment by dmik** [comment]
Okay, now I see what this patch is for.

However, first of all, we should find out why such (and actually all other) subdirectories in the Projects view are tagged with blue Qt Creator icons instead of the native folder icons as on other platforms (and as in the File System view on all platforms including OS/2).

Once we find the answer and fix the problem, we will end up with 20x20 WPS folder icons in the Projects view. So your fix will become just:

``` cpp
    setIconSize(Core::FileIconProvider::iconSize()); 
```

Of course, since stock Qt Creator icons are 16x16, we will have to deal with that. But it's not necessary to change the icons themselves. We just need to provide a common static function (something like FileIconProvider::getIcon()) that, given a pixmap resource ID (or how they initially load their stock icons in Qt Creator), will load it and center within the iconSize()'d box if it is larger. You already used this technique for overlays and I already used it in Qt (for example when setting 16x16 icons supplied by applications icons as 20x20 top level window icons).

**Comment by warped-rudi** [comment]
Creator uses the blue folder icons in project view, because the pixmaps are loaded from our style and not from the file icon provider.

**Comment by dmik** [comment]
This looks like a inconsistency to me. I think both the File System view and the Projects view should take icons from the FileIconProvider (which takes them from the style anyway -- so that it will not change anything on other platforms where icons in the native style match icons provided by file icon providers).

**Comment by warped-rudi** [comment]
It's not that simple. For example QFileIconProvider does not offer an icon for an open folder. This is only available from QStyle. Our current style implementation is also inconsistent, since ::icon(QFileInfo("C:/someFolder")) will return a different icon than ::icon(QFileIconProvider::Folder).

However, I now have a version that uses native icons in both File System and Projects view. I don't fully like the implementation, but please review it. Where should I put the diff ?

**Comment by dmik** [comment]
I see. Let's see what you got.

The best way to provide diffs here is to fork and then create a pull request. This requires a bit of reading about git and GitHub but once you've got it, such things will really become a lot easier for both you and me. If you don't have time for that right now, you may mail the diff to me. But please consider doing that in the near future -) Eventually, all patches will only be accepted through this mechanism.

**Comment by warped-rudi** [comment]
Sent to you via private mail.

**Comment by dmik** [comment]
I got your patch, sorry for the delay, I was busy with the RPM task a lot. Looking at it.

**Comment by dmik** [comment]
This was a good attempt but honestly it looks like too much of platform dependent code.

So I moved the dirty work to Qt itself (QCommonStyle) to hide it there, see http://svn.netlabs.org/qt4/changeset/1028. Other Qt applications will benefit from that too I think (as they will not have to deal with the inconsistency that was there before and that you tried to solve by your patch on the Qt Creator level).

This way, nothing but replacing QSize(16,16) with FileIconProvider::iconSize() is necessary (as we discussed earlier). So I only applied this part of your patch in 32b14d7e. Thanks, as usual. I think this issue may be closed now.

BTW, I see you started trying git out -) Very good
